version: "3"

services:
  backend:
    build: "./backend"
    volumes:
      - ./backend:/var/www/html
    ports:
      - 8080:80
  frontend:
    build: "./frontend"
    ports:
      - 7070:80
    volumes:
      - ./frontend:/var/www/frontend
  db:
    image: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: TKmxbQv6e3Q4Zc
