export { default as Home } from './Home.jsx';
export { default as Products } from './Products.jsx';
export { default as Product } from './Product.jsx';
export { default as Cart } from './Cart.jsx';
export { default as Register } from './Register.jsx';
export { default as Account } from './Account.jsx';
export { default as Account_managment } from './Account_managment.jsx';
export { default as Settings } from './Settings/Settings.jsx';
export { default as PageNotFound } from './PageNotFound.jsx';
